name: test
run-name: ${{ github.actor }} is pushing
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  pipeline:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v2
      - name: Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm i
        run: npm install
      - name: build prod
        run: npm run build:prod
      - name: eslint
        run: lint:ts
      - name: lint styles
        run: npm run list:scss
      - name: unit tests
        run: npm run unit
